import Mathlib.GroupTheory.FreeGroup.Reduce

/-!
# Finite automata for finitely generated subgroups of a free group

For each finite list of signed words, the proposition below asks for a finite
partial automaton over the two free generators. Its transition table must
pair every edge with its inverse, and traversal of the canonical reduced word
must recognize exactly the subgroup generated by the input list.

The acceptance semantics are written directly with `List.foldl` so this
statement file depends only on Mathlib's free-group representation, not on the
implementation being verified.
-/

namespace Stallings

/-- Complete mathematical statement of finite-automaton recognition for a
finite list of words in `FreeGroup (Fin 2)`. -/
def completeStatement (S : List (List (Fin 2 × Bool))) : Prop :=
  ∃ (V : Type) (_ : Fintype V) (base : V)
    (next : V → (Fin 2 × Bool) → Option V),
    (∀ v x w, next v x = some w → next w (x.1, !x.2) = some v) ∧
    ∀ g : FreeGroup (Fin 2),
      (let run : List (Fin 2 × Bool) → Option V := fun word =>
        word.foldl (fun state letter =>
          state.bind fun vertex => next vertex letter) (some base)
       run (FreeGroup.toWord g) = some base) ↔
        g ∈ Subgroup.closure
          (Set.range fun i : Fin S.length => FreeGroup.mk (S.get i))

/-- Every finitely generated subgroup of `FreeGroup (Fin 2)` has a finite
inverse-labelled automaton whose canonical-word traversal decides membership.
The solution supplies this automaton by the executable Stallings folding
construction. -/
theorem folded_recognizer_exists (S : List (List (Fin 2 × Bool))) :
    completeStatement S := by
  sorry

end Stallings
